@baseUrl = https://chessrumble.azurewebsites.net/

### Try to login an unknow 
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"nobody",
    "password":"nobody"
}


### Create an user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"Emma",
    "password":"Emma"
}

### Create an existing user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"Emma",
    "password":"Emma"
}

### Login an  user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"Emma",
    "password":"Emma"
}
