@baseUrl = http://localhost:3000

######### NORMAL OPERATION  ###########
### Read all games
GET {{baseUrl}}/games
### Read all games of a user
GET {{baseUrl}}/games?user=diego

### Read game identified by 2
GET {{baseUrl}}/games/2

#### Create a game
POST {{baseUrl}}/games
Content-Type: application/json

{
    "player":"josued00",
    "opponent":"diego",
    "winner": "diego",
    "moves": "Pawn:0,6-0,5;Pawn:3,1-3,2;Pawn:3,6-3,5;Bishop:2,0-3,1;Pawn:2,6-2,4;Pawn:4,1-4,2;Bishop:2,7-3,6;Bishop:3,1-2,2;Pawn:5,6-5,5;Bishop:2,2-3,1;Pawn:6,6-6,4;Queen:3,0-7,4"
}

### Delete game identified by 2
DELETE {{baseUrl}}/games/2

### Update the game identified by 4
PATCH {{baseUrl}}/games/4
Content-Type: application/json

{
    "moves":"Pawn:0,6-0,4;Pawn:3,1-3,2;Pawn:3,6-3,5;Bishop:2,0-3,1;Pawn:2,6-2,4;Pawn:4,1-4,2;Bishop:2,7-3,6;Bishop:3,1-2,2;Pawn:5,6-5,5;Bishop:2,2-3,1;Pawn:6,6-6,4;Queen:3,0-7,4"
}




######### ERROR OPERATION  ###########
GET {{baseUrl}}/games/100

### Create a game which lacks a property
POST {{baseUrl}}/games
Content-Type: application/json

{
    "moves":"Pawn:0,6-0,5;Pawn:3,1-3,2;Pawn:3,6-3,5;Bishop:2,0-3,1;Pawn:2,6-2,4;Pawn:4,1-4,2;Bishop:2,7-3,6;Bishop:3,1-2,2;Pawn:5,6-5,5;Bishop:2,2-3,1;Pawn:6,6-6,4;Queen:3,0-7,4"
}

### Update for a game which does not exist
PATCH {{baseUrl}}/games/200
Content-Type: application/json

{
    "moves":"Pawn:0,6-0,5;Pawn:3,1-3,2;Pawn:3,6-3,5;Bishop:2,0-3,1;Pawn:2,6-2,4;Pawn:4,1-4,2;Bishop:2,7-3,6;Bishop:3,1-2,2;Pawn:5,6-5,5;Bishop:2,2-3,1;Pawn:6,6-6,4;Queen:3,0-7,4"
}