######### NORMAL OPERATION  ###########

### Read all games
GET http://localhost:3000/games

### Read all games with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/games

### Read all games sorted by date (ascending)
GET {{baseUrl}}/games/?order=+date

### Read all games sorted by date (descending)
GET {{baseUrl}}/games/?order=-date

### Read game identified by 2
GET {{baseUrl}}/games/2

### Create a game by using the admin account
#### First login as the admin
##### Define a request variable nammed admin
# @name admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

#### Create a game with the admin token
POST {{baseUrl}}/games
Content-Type: application/json

{
    "player1":"Grosué",
    "player2":"Diegs",
    "winner": "Diegs",
    "moves": "G2,H4,Z5"
}

### Delete game identified by 2 with the admin token
DELETE {{baseUrl}}/games/2

### Update the game identified by 6 with the admin token
PATCH {{baseUrl}}/games/6
Content-Type: application/json

{
    "moves":"D5,H2,I4"
}




######### ERROR OPERATION  ###########

### 1. Create a game without a token
POST {{baseUrl}}/games
Content-Type: application/json

{
    "title":"Magic Green",
    "content":"Epinards, Brocolis, Olives vertes, Basilic"
}

### 2. Create a game without being the admin, use manager account
#### 2.1 First login as the manager
##### 2.1.1 Define a request variable nammed manager
# @name manager
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"manager",
    "password":"manager"
}

##### 2.1.2 Define a file variable to simplify the access to the token of manager
@managerToken = {{manager.response.body.token}}

#### 2.2 Try to create a game with the manager token
POST {{baseUrl}}/games
Content-Type: application/json
Authorization: {{managerToken}}

{
    "title":"Magic Green",
    "content":"Epinards, Brocolis, Olives vertes, Basilic"
}

### Read game which does not exists
GET {{baseUrl}}/games/100

### Create a game which lacks a property
POST {{baseUrl}}/games
Content-Type: application/json

{
    "content":"Epinards, Brocolis, Olives vertes, Basilic"
}

### Create a game without info for a property
POST {{baseUrl}}/games
Content-Type: application/json

{
    "title":"",
    "content":"Epinards, Brocolis, Olives vertes, Basilic"
}

### Update for a game which does not exist
PATCH {{baseUrl}}/games/200
Content-Type: application/json
Authorization: {{admin.response.body.token}}

{
    "title":"Magic Green 2"
}

### Update for a game which does not provide any info for a property
PATCH {{baseUrl}}/games/1
Authorization: {{admin.response.body.token}}

Content-Type: application/json

{
    "title":"Magic Green 2",
    "content":""
}